### ISSUE TITLE
Confusion about VM installation step

### ISSUE THREAD

**Issue by Lelouny** [0xricksanchez/fisy-fuzz#1]
Are there any requirements for the **iso** file used when installing VM with the **virt-install** command? Do I still use the ubuntu 18.04 iso file?

**Comment by 0xricksanchez** [comment]
Originally, Ubuntu 18.04 was used as the Host OS to test this fuzzer. Using Ubuntu 22.04 may work but it may need some adjustments within the `Requirements.sh`. 
The VMs used to do the actual fuzzing (creation of filesystems as well as the mounting + accessing corrupted file systems) don't have to be Ubuntu. I was testing OpenBSD, NetBSD, and FreeBSD at the time. If you want to test Ubuntu filesystems you would use a Ubuntu based iso file for that :). Hope that clarifies things!
